git:
  name: "Timo Sugliani"
  email: "timo.sugliani@gmail.com"

ssh:
  personal_pubkey: "~/.ssh/id_ed25519.pub"

use_1password: false

op:
  vault: "Personal"
  ssh_personal_item:    "SSH-Personal"
  ssh_zpods_item:       "SSH-zPodFactory"
  github_personal_item: "GitHub-Personal"

packages:
  linux:
    apt:
      - bat
      - eza
      - fd-find
      - fzf
      - git
      - git-delta
      - lazygit
      - ripgrep
      - starship
      - tmux
      - zoxide
    homebrew:
      - neovim
      - oh-my-posh
  darwin:
    homebrew:
      - bat
      - eza
      - fd
      - fzf
      - git
      - git-delta
      - lazygit
      - neovim
      - oh-my-posh
      - ripgrep
      - starship
      - tmux
      - zoxide
