git:
  name: "Timo Sugliani"
  email: "timo.sugliani@gmail.com"

ssh:
  personal_pubkey: "~/.ssh/id_ed25519.pub"
  work_pubkey:     "~/.ssh/id_ed25519_work.pub"

use_1password: false

op:
  vault: "Private"
  ssh_personal_item:    "SSH Personal"
  ssh_work_item:        "SSH Work"
  github_personal_item: "GitHub"
  github_work_item:     "GitHub Work"

packages:
  linux:
    apt:
      - bat
      - eza
      - fd-find
      - fzf
      - git
      - git-delta
      - lazygit
      - ripgrep
      - starship
      - tmux
      - zoxide
    homebrew:
      - neovim
      - oh-my-posh
  darwin:
    homebrew:
      - bat
      - eza
      - fd
      - fzf
      - git
      - git-delta
      - lazygit
      - neovim
      - oh-my-posh
      - ripgrep
      - starship
      - tmux
      - zoxide
